webapp/client/__init__.py
from flask import Blueprint, current_app
from shipka.manager import app

client = Blueprint('client', __name__,
                   static_folder='static',
                   static_url_path='/static/client',
                   template_folder='templates')

from . import views

webapp/client/views.py
from flask import render_template, redirect, url_for, flash
from flask import request
from flask_login import current_user, login_required
from flask_socketio import join_room, emit

from shipka.store import database
from shipka.webapp import socketio
from shipka.webapp.registries import MODELS_REGISTRY
from shipka.webapp.views.crudy_integration import build_ctx
from shipka.webapp.util import get_latest, get_now_user, get_user
from webapp.api.common import build_user_ctx
from webapp.api.models import UserView, InboxEntry, GroupGoal, ProddayApp, GroupGoalUserSettings
from webapp.client import client
from webapp.init_user import init_user
from webapp.registries import build_dependencies


@client.route('/')
def get_home():
    user = get_user(create=False)
    if user and user.is_authenticated:
        user_views = UserView.get_all_by(user=user)
        if not user_views:
            user_views = init_user(user)
        sorted_user_views = sorted(user_views, key=lambda x: x.order)
        user_view_id = sorted_user_views[0].id
        return redirect(url_for('client.get_view', user_view_id=user_view_id))
    return render_template("index.html")


@client.route('/views/<int:user_view_id>')
@login_required
def get_view(user_view_id):
    user = get_user()
    user_view = UserView.get_one_by(user=user, id=user_view_id)
    if not user_view:
        flash('Error getting view id {}.'.format(user_view_id))
        return redirect('/')
    ctx = build_ctx()
    ctx.update(build_user_ctx(user))
    model_scripts, view = build_dependencies(ctx['model_scripts'], user_view.view_components)
    ctx['user_view'] = user_view
    ctx['view'] = view
    return render_template('view.html',
                           title="Prod Day - User View",
                           **ctx)


@client.route('/group_goals/<int:group_goal_id>')
@login_required
def get_group_goal(group_goal_id):
    user = get_user()
    group_goal = GroupGoal.get_one_by(id=group_goal_id)
    if not group_goal:
        flash('Error getting group goal id {}'.format(group_goal_id))
        return redirect('/')

    if group_goal.visibility == GroupGoal.VISIBILITY_MEMBERS:
        # If the group goal should be visible to members only
        group_goal_user_settings = GroupGoalUserSettings.get_one_by(group_goal_id=group_goal_id,
                                                                    user_id=user.id)
        if not group_goal_user_settings:
            flash('Error getting group goal id {}'.format(group_goal_id))
            return redirect('/')
    user_view = group_goal.user_view
    ctx = build_ctx()
    ctx.update(build_user_ctx(user))
    model_scripts, view = build_dependencies(ctx['model_scripts'], user_view.view_components)
    ctx['model_scripts'] = model_scripts
    ctx['view'] = view
    return render_template('view.html',
                           group_goal=group_goal,
                           title="Prod Day - Group Goal",
                           **ctx)


@client.route('/search')
@login_required
def get_search_results():
    user = get_user()
    q = request.args.get('q')
    try:
        entries = InboxEntry.query. \
            whooshee_search(q). \
            filter_by(user=current_user).all()
    except ValueError as e:
        entries = []
        flash(e)
    ctx = build_ctx()
    ctx.update(build_user_ctx(user))
    return render_template('search_results.html',
                           q=q,
                           entries=entries,
                           title='Prod Day - Search "%q"'.format(q),
                           **ctx)


@socketio.on('components_syn')
def socket_connect(json):
    payload = {}
    if current_user.is_authenticated:
        tz_offset_minutes = json.get('tz_offset_minutes')
        tz_offset_seconds = -(tz_offset_minutes * 60)
        if current_user.tz_offset_seconds != tz_offset_seconds:
            current_user.tz_offset_seconds = tz_offset_seconds
            database.add(current_user)
            database.push()
        model_updates = {}
        for model_name in MODELS_REGISTRY:
            model_updates[model_name] = get_latest(model_name)
        join_room(current_user.id)
        payload = {'user': {'id': current_user.id},
                   'request_sid': request.sid,
                   'datetime': str(get_now_user(current_user)),
                   'models_updates': model_updates}
    print('< components_syn: ' + str(json))
    print('> components_ack: ' + str(payload))
    emit('components_ack', payload)

webapp/client/templates/favicons.html
<link rel="apple-touch-icon" sizes="57x57" href="{{ url_for('static', filename='client/img/favicons/apple-icon-57x57.png')}}">
<link rel="apple-touch-icon" sizes="60x60" href="{{ url_for('static', filename='client/img/favicons/apple-icon-60x60.png')}}">
<link rel="apple-touch-icon" sizes="72x72" href="{{ url_for('static', filename='client/img/favicons/apple-icon-72x72.png')}}">
<link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename='client/img/favicons/apple-icon-76x76.png')}}">
<link rel="apple-touch-icon" sizes="114x114" href="{{ url_for('static', filename='client/img/favicons/apple-icon-114x114.png')}}">
<link rel="apple-touch-icon" sizes="120x120" href="{{ url_for('static', filename='client/img/favicons/apple-icon-120x120.png')}}">
<link rel="apple-touch-icon" sizes="144x144" href="{{ url_for('static', filename='client/img/favicons/apple-icon-144x144.png')}}">
<link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename='client/img/favicons/apple-icon-152x152.png')}}">
<link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='client/img/favicons/apple-icon-180x180.png')}}">
<link rel="icon" type="image/png" sizes="192x192"  href="{{ url_for('static', filename='client/img/favicons/android-icon-192x192.png')}}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='client/img/favicons/favicon-32x32.png')}}">
<link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename='client/img/favicons/favicon-96x96.png')}}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='client/img/favicons/favicon-16x16.png')}}">
<link rel="manifest" href="{{ url_for('static', filename='client/img/favicons/manifest.json')}}">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">

webapp/client/templates/forms/forgot_password.html
{% import "_macros.html" as macros %}
<form method="post" action="/reset">
    <input type="hidden" name="next" value="{{ request.args.next }}"/>
  {{ forgot_password_form.csrf_token() }}
  {{ macros.form_field(forgot_password_form, forgot_password_form.email, class="form-control") }}<br>
    <br>
  {{ forgot_password_form.submit(class="btn-primary form-control") }}<br>
</form>

webapp/client/templates/forms/login.html
{% import "_macros.html" as macros %}
<form class="action" method="post" action="/login" id="login-form">
    {{ login_form.hidden_tag() }}
    {{ macros.form_field(login_form, login_form.email, width=12) }}
    {{ macros.form_field(login_form, login_form.password, width=12) }}
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="remember-me-check" name="remember">
        <label class="form-check-label" for="remember-me-check">Remember me</label>
    </div>
    <div class="row" style="margin-top: 30px;">
        <input id="login-form-submit" class="btn btn-primary btn-block" name="submit" type="submit" value="Login">
    </div>
</form>

webapp/client/templates/forms/register.html
{% import "_macros.html" as macros %}
<form class="action" method="post" action="/register" id="register-form">
    {{ signup_form.hidden_tag() }}
    {{ macros.form_field(signup_form, signup_form.name, width=12) }}<br>
    {{ macros.form_field(signup_form, signup_form.email, width=12) }}<br>
    {{ macros.form_field(signup_form, signup_form.password, width=12) }}<br>
    {{ macros.form_field(signup_form, signup_form.password_confirm, width=12) }}<br>
    <div class="row" style="margin-top: 30px;">
        <input id="register-form-submit" class="btn btn-primary btn-block" name="submit" type="submit" value="Register">
    </div>
</form>

webapp/client/templates/index.html
{% extends "layout.html" %}

{% block style %}
    <style>
        body {
            background-image: url("{{ url_for('client.static', filename='img/space.jpg') }}");
            background-color: #cccccc;
        }
        .main-card {
            position: absolute;
            top: 100px;
            left: 100px;
            width: 40rem;
        }
    </style>
{% endblock %}

{% block content %}
    {% include "navigation.html" %}
    <div class="card main-card">
        <div class="card-body">
            <h1 class="card-title">Put a car in SPACE!</h1>
            <h4 class="card-subtitle mb-2 text-muted">Prodday is the one place for all your productivity needs!</h4>
            <p class="card-text">Organize your day, your week, your month or even your year with:
            <ul>
                <li>Tasks</li>
                <li>Events</li>
                <li>Projects</li>
                <li>Goals</li>
                <li>Trackers</li>
                <li>Activities</li>
            </ul>
            and many more.</p>
            <h4><a href="/register" class="btn btn-primary btn-lg">Sign up</a> to get an early access.</h4>
        </div>
    </div>
{% endblock %}

{% block script %}{% endblock %}

webapp/client/templates/layout_main.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ title or "App" }}</title>
    {% include "favicons.html" %}
    {% import "_macros.html" as macros %}
    {{ macros.include_css('layout') }}
    {% if user_settings.background_img_url %}
        <style>
            body {
                background-image: url("{{ url_for('client.static', filename='{{ user_settings.background_img_url }}') }}");
            }
        </style>
    {% endif %}
    {% block style %}{% endblock %}
</head>
<body>
{% include "modal.html" %}
{% include "navigation.html" %}
<div id="flashed-messages-container" style="position:relative; top: 64px; z-index: 999;">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{% if category == 'message' %}danger{% else %}{{ category }}{% endif %}
            alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
</div>
<div class="container-fluid" style="position: relative; top: 65px;">
    <div class="row">
        <div class="col-2 d-none d-xs-none d-sm-none d-md-block" style="padding:0; top: 5px">
            <ul class="side-nav nav flex-column nav-pills">
                {% for uv in user_views %}
                    {% if uv.on_main %}
                        <li class="nav-item">
                            <a href="/views/{{ uv.id }}"
                               class="nav-link side-nav-link {% if user_view and user_view.name ==  uv.name %}active{% endif %}">
                                <span style="display: inline-block; width: 40px"><i
                                        class="fa fa-{{ uv.icon }} fa-lg"></i></span>
                                {{ uv.name|capitalize }}
                            </a>
                        </li>
                    {% endif %}
                {% endfor %}
                <hr>
                {% for group_goal in group_goals %}
                    <p><a class="nav-link side-nav-link" href="/group_goals/{{ group_goal.id }}">
                        <i class="fa fa-users fa-lg"></i>
                        <span style="padding-left:20px;">{{ group_goal.name }}
                        </span>
                    </a></p>
                {% endfor %}
            </ul>
        </div>
        <div class="main-content col-xs-12 col-sm-12 col-md-10">
            {% block content %}{% endblock %}
        </div>
    </div>
    {% if crudy_templates %}
        {% for fe_template in crudy_templates %}
            <script type="text/x-template" id='fe-template-core-{{ fe_template.split('.')[0] }}'>
                {% include '/crudy/templates/' + fe_template %}
            </script>
        {% endfor %}
    {% endif %}
    {% if user.notifications_enabled %}
        <script type="text/x-template" id='fe-template-notification-container'>
            {% include 'notifications/container.html' %}
        </script>
        {% for fe_template in notification_templates %}
            <script type="text/x-template" id='fe-template-notification-text-title-{{ fe_template }}'>
                {% include 'notifications/' + fe_template + '/title.html' %}
            </script>
            <script type="text/x-template" id='fe-template-notification-text-body-{{ fe_template }}'>
                {% include 'notifications/' + fe_template + '/body.html' %}
            </script>
        {% endfor %}
    {% endif %}
    {% for fe_template in edit_templates %}
        <script type="text/x-template" id='fe-template-edit-{{ fe_template.split('.')[0] }}'>
            {% include fe_template %}
        </script>
    {% endfor %}

    <script>
      var USER_TIMEZONE = "{{ (user.tz_offset_seconds/3600)|float_to_tz }}";
      var DEBUG = {% if config.DEBUG %}true{% else %}false{% endif %}
      {% if models %}
        var MODELS = {
          {% for model in models.itervalues() %}
            "{{ model.name }}":
              {
                name: "{{ model.name }}",
                nameHuman: "{{ model.human_name }}",
                namePlural: "{{ model.name_plural }}",
                defaults: {},
                constants: {{ model.model_constants|tojson }},
                elements: {{ model.elements|tojson }},
                modelMethods: function (ctx) {
                  return {}
                },
                collectionMethods: function (ctx) {
                  return {}
                }
              },
          {% endfor %}
        };
      {% endif %}
    </script>
    {{ macros.include_js('layout') }}
    <script>
      $('.side-nav-toggle').on('click', function () {
        $('.side-nav').animate({
          width: "toggle"
        }, function () {
          if ($('.side-nav').is(':visible')) {
            console.log('visible');
            $('.main-content ').removeClass('col-md-12').addClass('col-md-10');
          } else {
            console.log('invisible');
            $('.main-content ').removeClass('col-md-10').addClass('col-md-12');
          }
        });
      });
    </script>
    <script src="{{ url_for('api.static', filename="models.js") }}"></script>
    {% if user.notifications_enabled %}
        <script src="{{ url_for('api.static', filename="notifications.js") }}"></script>
    {% endif %}
    {% block script %}{% endblock %}
    <script src="{{ url_for('api.static', filename="views.js") }}"></script>
</body>
</html>

webapp/client/templates/modal.html
<div class="modal fade" id="worldwide-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Note</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button class="btn btn-lg pull-right dropdown-toggle highlightable"
                        data-toggle="dropdown" style="background-color: initial;">
                    <i class="fa fa-ellipsis-v"></i>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item action-delete" href="#">Delete</a>
                </div>
                <button type="button" class="btn btn-primary action-save">Save changes</button>
            </div>
        </div>
    </div>
</div>

webapp/client/templates/navigation.html
{% if user_settings and user_settings.contexts_enabled %}
    <nav class="navbar navbar-expand-lg navbar-{{ context.fg_color or "dark" }} fixed-top"
         style="background-color: {{ context.color or "#333" }}; color: white; box-shadow: 0 1px 5px grey;">
{% else %}
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top"
         style="background-color: #333; color: white; box-shadow: 0 1px 5px grey;">
{% endif %}
<a class="navbar-brand side-nav-toggle" href="#">
    <i class="fa fa-bars"></i>
</a>
<a class="navbar-brand" href="/">Prodday</a>
<div class="navbar-expand">
    {%- if current_user.is_authenticated and user_settings.search_enabled %}
        <form class="form-inline" action="{{ url_for('client.get_search_results') }}">
            <div class="nav-search-wrapper">
                <i class="fa fa-search fa-lg" style="z-index:1"></i>
                <input class="form-control nav-search" type="search" placeholder="Search"
                        {% if user_settings.contexts_enabled %}
                       style="background-color: {{ context.color or "#333" }};"
                        {% else %}
                       style="background-color: #333;"
                        {% endif %}
                       aria-label="Search"
                       name="q" value="{{ q }}">
            </div>
        </form>
    {% endif %}
</div>
<div class="navbar-expand ml-auto" id="navbarSupportedContent">
    <ul class="navbar-nav">
        {%- if current_user.is_authenticated %}
            {% if user_settings.search_enabled %}
                <li class="nav-item dropdown" id="navbar-search">
                    <a class="nav-link d-xs-block d-sm-none" href="#" id="navbar-search-link" role="button"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-search fa-lg"></i>
                    </a>
                </li>
            {% endif %}
            {% if user_settings.contexts_enabled and contexts %}
                <li class="nav-item dropdown" id="navbar-dropdown-context">
                    <a class="nav-link dropdown-toggle" href="#" id="navbar-dropdown-context-link" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-at fa-lg"></i>
                        <span class="badge" style="background-color: {{ context.color }};">{{ context.name }}</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right context-container"
                         aria-labelledby="navbarDropdownContextt" style="width:200px;">
                        {% for context in contexts %}
                            <a class="dropdown-item" href="#">
                                <span class="badge" style="background-color: {{ context.color }}; color: white;"><i
                                        class="fa fa-at fa-lg"></i> {{ context.name }}</span>
                            </a>
                        {% endfor %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            No context
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            Auto-Context:
                            <label class="switch pull-right">
                                <input type="checkbox">
                                <span class="slider round"></span>
                            </label>
                        </a>
                    </div>
                </li>
            {% endif %}
            {% if user_settings.notifications_enabled %}
                <li class="nav-item dropdown" id="navbar-dropdown-bell">
                    <a class="nav-link dropdown-toggle" href="#" id="navbar-dropdown-bell-link" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-bell fa-lg"></i>
                        <span class="badge badge-danger notifications-count" style="display: none;">0</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right notifications-container"
                         aria-labelledby="navbarDropdownBell" style="width:400px;">
                        <a class="dropdown-item" href="#">No notifications</a>
                    </div>
                </li>
            {% endif %}
            <li class="nav-item dropdown" id="navbar-dropdown-profile">
                <a class="nav-link dropdown-toggle" href="#" id="navbar-dropdown-profile-link" role="button"
                   data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <img src="{{ user.email|gravatar }}" class="rounded-circle"
                         style="height: 32px;"/> {{ user.name }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                    <a class="dropdown-item" href="/logout">Log Out</a>
                </div>
            </li>
        {% else %}
            <a href="/login" class="btn btn-primary">Login</a>
            <a href="/register" class="btn btn-success">Register</a>
        {% endif %}
    </ul>
</div>
</nav>

webapp/client/templates/new_edit.html
{% extends "layout_main.html" %}

{% block style %}
{% endblock %}

{% block content %}

    <div id="root" class="container">
        <div class="row">
            <div class="col-8">
                <h2>
                    {% if instance_id %}
                        Edit
                    {% else %}
                        New
                    {% endif %}
                    {{ models[view.collection_name].name_human|capitalize }}
                </h2>
            </div>
            <div class="col-4">
                <button class="btn btn-lg secondary-action"></button>
                <button type="submit" class="btn btn-lg btn-primary submit">Save</button>
            </div>
        </div>
        <hr>
    </div>
    {% for api_name, fe_template in view.templates %}
        <script type="text/x-template" id='fe-template-{{ fe_template.split('.')[0] }}'>
            {% include fe_template %}
        </script>
    {% endfor %}
{% endblock %}

{% block script %}
    <script>
      {% if instance_id %}
        var INSTANCE_ID = parseInt("{{ instance_id }}");
      {% endif %}
      var FE_TEMPLATE = "#fe-template-{{ view.model_name }}";
      var COLLECTION_NAME = "{{ view.collection_name }}";
    </script>
    {% if instance_id %}
        <script src="{{ url_for('client.static', filename='js/edit.js') }}"></script>
    {% else %}
        <script src="{{ url_for('client.static', filename='js/new.js') }}"></script>
    {% endif %}
{% endblock %}

webapp/client/templates/search_results.html
{% extends "layout_main.html" %}

{% block style %}
{% endblock %}

{% block content %}
    {% if not entries %}
        <p>No results for <strong>{{ q }}</strong></p>
    {% endif %}
    {% for entry in entries %}
        <blockquote>
            <h4>{{ loop.index }}. InboxEntry | {{ entry.created_ts|format_dt("%A, %d %B") }} | {{ entry.created_ts|format_dt("%H:%M") }}
            </h4>
            <p>{{ entry.body|hl_search(q, 3)|safe }}</p>
        </blockquote>
    {% endfor %}
{% endblock %}

{% block script %}
{% endblock %}

webapp/client/templates/security/change_password.html
{% extends "layout.html" %}
{% import "_macros.html" as macros %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-4 col-md-offset-4">
              {% if current_user.temp_password %}
                  <div class="alert alert-warning">
                      {{ gettext('You are using a temporarily generated password. Please change below') }}
                  </div>
              {% endif %}
                <div class="well">
                    <h2>{{ gettext('Change password') }}</h2>

                    <form action="{{ url_for_security('change_password') }}" method="POST" name="change_password_form">
                      {{ change_password_form.hidden_tag() }}
                      {% if current_user.temp_password %}
                          <strong>{{ gettext('Temporary password') }}</strong><br>
                          <p>{{ current_user.temp_password }}</p>
                          <input type="hidden" class="form-control" value="{{ current_user.temp_password }}"
                                 name="password" id="password"/>
                      {% else %}
                        {{ macros.form_field(change_password_form, change_password_form.password, class="form-control") }}
                      {% endif %}<br>
                      {{ macros.form_field(change_password_form, change_password_form.new_password, class="form-control") }}<br>
                      {{ macros.form_field(change_password_form, change_password_form.new_password_confirm, class="form-control") }}
                        <br>
                      {{ change_password_form.submit(class="btn btn-primary form-control") }}<br>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

webapp/client/templates/security/forgot_password.html
{% extends "layout.html" %}

{% import "_macros.html" as macros %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-4 col-md-offset-4">
                <h1>{{ gettext('Send password reset instructions') }}</h1>
                <div class="well">
                  {% include "forms/forgot_password.html" %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

webapp/client/templates/security/login_user.html
{% extends "layout.html" %}

{% block style %}
    <style>
        body {
            background-image: url("{{ url_for('client.static', filename='img/space.jpg') }}");
            background-color: #cccccc;
        }

        .main-card {
            position: absolute;
            top: 100px;
            left: 100px;
            width: 40rem;
        }
    </style>
{% endblock %}

{% import "_macros.html" as macros %}
{% block content %}
    {% include "navigation.html" %}
    <div class="card main-card">
        <div class="card-body">
            <h1 class="card-title">Log in</h1>
            <p class="card-text">
                {% set login_form = login_user_form %}
                {% include "forms/login.html" %}
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
      // paranoicaly, clean the local storage data
      localStorage.clear();

      $('#register-form').on('submit', function () {
        var emailEl = $(this).find('#email');
        emailEl.val(emailEl.val().trim());
        $('#register-form-submit').prop('disabled', true);
      });
    </script>
{% endblock %}

webapp/client/templates/security/register_user.html
{% extends "layout.html" %}

{% block style %}
    <style>
        body {
            background-image: url("{{ url_for('client.static', filename='img/space.jpg') }}");
            background-color: #cccccc;
        }

        .main-card {
            position: absolute;
            top: 100px;
            left: 100px;
            width: 40rem;
        }
    </style>
{% endblock %}

{% import "_macros.html" as macros %}
{% block content %}
    {% include "navigation.html" %}
    <div class="card main-card">
        <div class="card-body">
            <h1 class="card-title">Register</h1>
            <p class="card-text">
                {% set signup_form = register_user_form %}
                {% include "forms/register.html" %}
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
      // paranoicaly, clean the local storage data
      localStorage.clear();

      $('#register-form').on('submit', function () {
        var emailEl = $(this).find('#email');
        emailEl.val(emailEl.val().trim());
        $('#register-form-submit').prop('disabled', true);
      });
    </script>
{% endblock %}

webapp/client/templates/security/send_confirmation.html
{% extends "layout.html" %}
{% import "_macros.html" as macros %}
{% if get_flashed_messages() and get_flashed_messages()|length > 0 %}
  {% set email=get_flashed_messages()[0].split('to ')[1][:-1] %}
{% endif %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-4 col-md-offset-4">


                <div class="well">
                    <h2>{{ gettext('Resend confirmation instructions') }}</h2>

                    <form action="{{ url_for_security('send_confirmation') }}" method="POST"
                          name="send_confirmation_form">
                      {{ send_confirmation_form.hidden_tag() }}
                      {{ macros.form_field(send_confirmation_form, send_confirmation_form.email, class="form-control", value=email) }}
                      {{ send_confirmation_form.submit(class="btn btn-primary form-control") }}<br>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

webapp/client/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="progress-goal-circle"></div>
<script src="/static/client/js/vendor/jquery.js"></script>
<script src="/static/client/js/vendor/progressbar.js"></script>
<script>
  var bar = new ProgressBar.Circle($('.progress-goal-circle')[0], {
    strokeWidth: 6,
    easing: 'easeInOut',
    duration: 1400,
    color: '#36a',
    trailColor: '#eee',
    trailWidth: 1,
    svgStyle: null
  });

  bar.animate(0.4, {
    to: {color: '#6a3'},
    from: {color: '#36a'},
    step: function (state, circle, attachment) {
      circle.path.setAttribute('stroke', state.color);
    }
  });
</script>
</body>
</html>